TRAIN:
  epoches:      100
  ep_size:      600
  batch_size:   16
  save_ep:      10

  num_readers:  4
  num_threads:  4

NET:
  img_size:     416
  grid_size:    13
  num_anchors:  5
  max_bboxes_per_img: 20
  num_classes:  20
  cls_offset:   1

  #thred_prob:   0.3  # NMS
  #thred_iou:    0.5  # NMS
  anchors:    [[1.73145,1.32210],     # h, w, voc
               [4.00944,3.19275],
               [8.09892,5.05587],
               [4.84053,9.47112],
               [10.0071,11.2364]]
               
               #[[1., 1.],  # test
               # [1., 2.], 
               # [2., 1.], 
               # [2., 2.], 
               # [3., 2.]]
               
               #[[0.67738, 0.57273],  # h, w, coco
               #[2.06253, 1.87446],
               #[5.47434, 3.33843],
               #[3.52778, 7.88282],
               #[9.16828, 9.77052]]

LR:
  constant:
    lr:           0.0001 
  piecewise:
    boundaries:   [30000, 60000]
    values:       [0.001, 0.0005, 0.0001]
  exp:
    # exp(exponential_decay) # 0.9**20 = 0.1215
    lr:           0.0001
    decay_steps:  10000
    decay_rate:   0.9
    staircase:    False
  polynominal:
    lr:           0.0001
    end_lr:       0.00001
    decay_steps:  10000
    power:        1.0
    cycle:        False

OPTIM:
  sgd:
    # None
  mom:
    momentum: 0.9
  rms:
    momentum: 0.9
    decay:    0.9
  adagrad:
    initial_accumulator_value: 0.1
  adadelta:
    rho: 0.95
  adam:
    belta1:  0.9
    belta2:  0.999

PATH:
  train_data:
    dir : './data/tfrecords/'
    name: 'VOC2007'  # 'VOC2007', 'VOC212', ''
    split: 'all'     # 'train', 'trainval', 'all'

  test_data: ~

  checkpoint_dir: './checkpoints/'

  log_dir: './logs/'

  finetune:
    yolo_v2:
      path: ~
    resnet_v2_152:
      path: './net/finetune_weights/resnet_v2_152/resnet_v2_152.ckpt'
      checkpoint_exclude_scopes: ['global_step', 'pred', 'yolo_loss']
      model_name: ~                 #'resnet_v2_152'
      checkpoint_model_scope: ~     #'resnet_v2_152'
    resnet_v2_50:
      path: './net/finetune_weights/resnet_v2_50/resnet_v2_50.ckpt'
      checkpoint_exclude_scopes: ['global_step','pred', 'yolo_loss']
      model_name: ~                 #'resnet_v2_50'
      checkpoint_model_scope: ~     #'resnet_v2_50'

  restore:
    resnet_v2_50: './checkpoints/09-10-13-11-29/resnet_v2_50.ckpt-89'
    resnet_v2_152: './checkpoints/'

LOSS:
  thred_neg   : 0.5 
  warmup_steps: 1000
  weight_decay: 0.0
  lambda_cls  : 1.0
  lambda_coord: 5.0
  lambda_obj  : 1.0
  lambda_noobj: 1.0

GPU:
  gpu_memory_fraction:  0.9
  allow_growth:         True
  allow_soft_placement: True
